// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACi11kamFsK7YPm52obEFpkGjPylDGKQw',
    appId: '1:123001210665:web:573db4d930c22efc845938',
    messagingSenderId: '123001210665',
    projectId: 'monitoring-pir-dan-debu',
    authDomain: 'monitoring-pir-dan-debu.firebaseapp.com',
    databaseURL: 'https://monitoring-pir-dan-debu-default-rtdb.firebaseio.com',
    storageBucket: 'monitoring-pir-dan-debu.appspot.com',
    measurementId: 'G-XDEW6BKD22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPwFRZGBJ3GF61cuLjFFKEhp-BrNfyFc',
    appId: '1:123001210665:android:c29052cd01272323845938',
    messagingSenderId: '123001210665',
    projectId: 'monitoring-pir-dan-debu',
    databaseURL: 'https://monitoring-pir-dan-debu-default-rtdb.firebaseio.com',
    storageBucket: 'monitoring-pir-dan-debu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68Zs7Rld_EsTFC2S8G6E_CWuA1y5QKbY',
    appId: '1:123001210665:ios:70846ef5921fd7c1845938',
    messagingSenderId: '123001210665',
    projectId: 'monitoring-pir-dan-debu',
    databaseURL: 'https://monitoring-pir-dan-debu-default-rtdb.firebaseio.com',
    storageBucket: 'monitoring-pir-dan-debu.appspot.com',
    iosClientId: '123001210665-s67vs81elbo5t2m8lu7lgf4oig2fd4ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.apk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA68Zs7Rld_EsTFC2S8G6E_CWuA1y5QKbY',
    appId: '1:123001210665:ios:70846ef5921fd7c1845938',
    messagingSenderId: '123001210665',
    projectId: 'monitoring-pir-dan-debu',
    databaseURL: 'https://monitoring-pir-dan-debu-default-rtdb.firebaseio.com',
    storageBucket: 'monitoring-pir-dan-debu.appspot.com',
    iosClientId: '123001210665-s67vs81elbo5t2m8lu7lgf4oig2fd4ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.apk',
  );
}
